/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ProblemDetailsError } from '../errors/problemDetailsError';
import {
  ValidationProblemDetailsError,
} from '../errors/validationProblemDetailsError';
import {
  CredentialsCSharpUpdateProfileCommand,
  credentialsCSharpUpdateProfileCommandSchema,
} from '../models/credentialsCSharpUpdateProfileCommand';
import {
  CredentialsCSharpUpsertCommand,
  credentialsCSharpUpsertCommandSchema,
} from '../models/credentialsCSharpUpsertCommand';
import {
  CSharpCredentialsItem,
  cSharpCredentialsItemSchema,
} from '../models/cSharpCredentialsItem';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';

export class CSharpCredentialsController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiCredentialsCsharpGET(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CSharpCredentialsItem[]>> {
    const req = this.createRequest('GET', '/api/credentials/csharp');
    return req.callAsJson(array(cSharpCredentialsItemSchema), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiCredentialsCsharpPOST(
    body?: CredentialsCSharpUpsertCommand,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CSharpCredentialsItem>> {
    const req = this.createRequest('POST', '/api/credentials/csharp');
    const mapped = req.prepareArgs({
      body: [body, optional(credentialsCSharpUpsertCommandSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(cSharpCredentialsItemSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsCsharpByIdGET(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CSharpCredentialsItem>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/csharp/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(cSharpCredentialsItemSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsCsharpByIdDELETE(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/csharp/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async apiCredentialsCsharpByIdPATCH(
    id: string,
    body?: CredentialsCSharpUpdateProfileCommand,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(credentialsCSharpUpdateProfileCommandSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/credentials/csharp/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsCsharpPublishingProfileGET(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/csharp/${mapped.id}/publishing-profile`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(array(string()), requestOptions);
  }
}
