/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ProblemDetailsError } from '../errors/problemDetailsError';
import {
  ValidationProblemDetailsError,
} from '../errors/validationProblemDetailsError';
import {
  CredentialsJavaUpdateProfileCommand,
  credentialsJavaUpdateProfileCommandSchema,
} from '../models/credentialsJavaUpdateProfileCommand';
import {
  CredentialsJavaUpsertCommand,
  credentialsJavaUpsertCommandSchema,
} from '../models/credentialsJavaUpsertCommand';
import {
  JavaCredentialsItem,
  javaCredentialsItemSchema,
} from '../models/javaCredentialsItem';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';

export class JavaCredentialsController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiCredentialsJavaGET(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JavaCredentialsItem[]>> {
    const req = this.createRequest('GET', '/api/credentials/java');
    return req.callAsJson(array(javaCredentialsItemSchema), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiCredentialsJavaPOST(
    body?: CredentialsJavaUpsertCommand,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JavaCredentialsItem>> {
    const req = this.createRequest('POST', '/api/credentials/java');
    const mapped = req.prepareArgs({
      body: [body, optional(credentialsJavaUpsertCommandSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(javaCredentialsItemSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsJavaByIdGET(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<JavaCredentialsItem>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/java/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(javaCredentialsItemSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsJavaByIdDELETE(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/java/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async apiCredentialsJavaByIdPATCH(
    id: string,
    body?: CredentialsJavaUpdateProfileCommand,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(credentialsJavaUpdateProfileCommandSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/credentials/java/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsJavaPublishingProfileByIdGET(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/java/${mapped.id}/publishing-profile`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(array(string()), requestOptions);
  }
}
