/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { ProblemDetailsError } from '../errors/problemDetailsError';
import {
  ValidationProblemDetailsError,
} from '../errors/validationProblemDetailsError';
import {
  CredentialsPythonUpdateProfileCommand,
  credentialsPythonUpdateProfileCommandSchema,
} from '../models/credentialsPythonUpdateProfileCommand';
import {
  CredentialsPythonUpsertCommand,
  credentialsPythonUpsertCommandSchema,
} from '../models/credentialsPythonUpsertCommand';
import {
  PythonCredentialsItem,
  pythonCredentialsItemSchema,
} from '../models/pythonCredentialsItem';
import { array, optional, string } from '../schema';
import { BaseController } from './baseController';

export class PythonCredentialsController extends BaseController {
  /**
   * @return Response from the API call
   */
  async apiCredentialsPythonGET(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PythonCredentialsItem[]>> {
    const req = this.createRequest('GET', '/api/credentials/python');
    return req.callAsJson(array(pythonCredentialsItemSchema), requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async apiCredentialsPythonPOST(
    body?: CredentialsPythonUpsertCommand,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PythonCredentialsItem>> {
    const req = this.createRequest('POST', '/api/credentials/python');
    const mapped = req.prepareArgs({
      body: [body, optional(credentialsPythonUpsertCommandSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(pythonCredentialsItemSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsPythonByIdGET(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PythonCredentialsItem>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/python/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(pythonCredentialsItemSchema, requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsPythonByIdDELETE(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/python/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @param body
   * @return Response from the API call
   */
  async apiCredentialsPythonByIdPATCH(
    id: string,
    body?: CredentialsPythonUpdateProfileCommand,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      body: [body, optional(credentialsPythonUpdateProfileCommandSchema)],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/credentials/python/${mapped.id}`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.call(requestOptions);
  }

  /**
   * @param id
   * @return Response from the API call
   */
  async apiCredentialsPythonPublishingProfileGET(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string[]>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/api/credentials/python/${mapped.id}/publishing-profile`;
    req.throwOn(400, ValidationProblemDetailsError, 'Bad Request');
    req.throwOn(404, ProblemDetailsError, 'Not Found');
    req.defaultToError(ProblemDetailsError);
    return req.callAsJson(array(string()), requestOptions);
  }
}
