/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  ConfigurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDto,
  configurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDtoSchema,
} from './configurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDto';
import {
  ConfigurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDto,
  configurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDtoSchema,
} from './configurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDto';

export interface ConfigurationsJavaCommonJavaDistributionManagementDto {
  repository?: ConfigurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDto;
  snapShotRepository?: ConfigurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDto;
}

export const configurationsJavaCommonJavaDistributionManagementDtoSchema: Schema<ConfigurationsJavaCommonJavaDistributionManagementDto> = object(
  {
    repository: [
      'repository',
      optional(
        lazy(
          () =>
            configurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDtoSchema
        )
      ),
    ],
    snapShotRepository: [
      'snapShotRepository',
      optional(
        lazy(
          () =>
            configurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDtoSchema
        )
      ),
    ],
  }
);
