/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface ConfigurationsPythonCommonPythonLicenseDto {
  type?: TypeEnum;
  value?: string;
}

export const configurationsPythonCommonPythonLicenseDtoSchema: Schema<ConfigurationsPythonCommonPythonLicenseDto> = object(
  {
    type: ['type', optional(typeEnumSchema)],
    value: ['value', optional(string())],
  }
);
