/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsTypeScriptCommonTsBugsDto {
  url?: string | null;
  email?: string | null;
}

export const configurationsTypeScriptCommonTsBugsDtoSchema: Schema<ConfigurationsTypeScriptCommonTsBugsDto> = object(
  {
    url: ['url', optional(nullable(string()))],
    email: ['email', optional(nullable(string()))],
  }
);
