/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsPhpCommonPhpAuthorDto {
  name?: string | null;
  email?: string | null;
  homepage?: string | null;
  role?: string | null;
}

export const configurationsPhpCommonPhpAuthorDtoSchema: Schema<ConfigurationsPhpCommonPhpAuthorDto> = object(
  {
    name: ['name', optional(nullable(string()))],
    email: ['email', optional(nullable(string()))],
    homepage: ['homepage', optional(nullable(string()))],
    role: ['role', optional(nullable(string()))],
  }
);
