/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsPhpCommonPhpSupportDto {
  email?: string | null;
  issues?: string | null;
  forum?: string | null;
  wiki?: string | null;
  irc?: string | null;
  chat?: string | null;
  source?: string | null;
  docs?: string | null;
  rss?: string | null;
}

export const configurationsPhpCommonPhpSupportDtoSchema: Schema<ConfigurationsPhpCommonPhpSupportDto> = object(
  {
    email: ['email', optional(nullable(string()))],
    issues: ['issues', optional(nullable(string()))],
    forum: ['forum', optional(nullable(string()))],
    wiki: ['wiki', optional(nullable(string()))],
    irc: ['irc', optional(nullable(string()))],
    chat: ['chat', optional(nullable(string()))],
    source: ['source', optional(nullable(string()))],
    docs: ['docs', optional(nullable(string()))],
    rss: ['rss', optional(nullable(string()))],
  }
);
