/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsJavaCommonJavaDeveloperDto {
  name?: string;
  email?: string;
  organization?: string | null;
  organizationUrl?: string | null;
}

export const configurationsJavaCommonJavaDeveloperDtoSchema: Schema<ConfigurationsJavaCommonJavaDeveloperDto> = object(
  {
    name: ['name', optional(string())],
    email: ['email', optional(string())],
    organization: ['organization', optional(nullable(string()))],
    organizationUrl: ['organizationUrl', optional(nullable(string()))],
  }
);
