/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsPythonCommonPythonPersonDto {
  email?: string | null;
  name?: string | null;
}

export const configurationsPythonCommonPythonPersonDtoSchema: Schema<ConfigurationsPythonCommonPythonPersonDto> = object(
  {
    email: ['email', optional(nullable(string()))],
    name: ['name', optional(nullable(string()))],
  }
);
