/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDto {
  id?: string;
  name?: string | null;
  url?: string;
}

export const configurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDtoSchema: Schema<ConfigurationsJavaCommonJavaDistributionManagementDtoJavaSnapShotRepositoryDto> = object(
  {
    id: ['id', optional(string())],
    name: ['name', optional(nullable(string()))],
    url: ['url', optional(string())],
  }
);
