/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ConfigurationsJavaCommonJavaScmDto {
  connection?: string;
  developerConnection?: string;
  url?: string;
}

export const configurationsJavaCommonJavaScmDtoSchema: Schema<ConfigurationsJavaCommonJavaScmDto> = object(
  {
    connection: ['connection', optional(string())],
    developerConnection: ['developerConnection', optional(string())],
    url: ['url', optional(string())],
  }
);
