/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDto {
  id?: string | null;
  url?: string | null;
}

export const configurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDtoSchema: Schema<ConfigurationsJavaCommonJavaDistributionManagementDtoJavaRepositoryDto> = object(
  {
    id: ['id', optional(nullable(string()))],
    url: ['url', optional(nullable(string()))],
  }
);
