/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface ConfigurationsTypeScriptCommonTsRepositoryDto {
  type?: string | null;
  url?: string | null;
  directory?: string | null;
}

export const configurationsTypeScriptCommonTsRepositoryDtoSchema: Schema<ConfigurationsTypeScriptCommonTsRepositoryDto> = object(
  {
    type: ['type', optional(nullable(string()))],
    url: ['url', optional(nullable(string()))],
    directory: ['directory', optional(nullable(string()))],
  }
);
