/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsRubyUpsertCommand {
  name?: string;
  apiKey?: string;
}

export const credentialsRubyUpsertCommandSchema: Schema<CredentialsRubyUpsertCommand> = object(
  { name: ['name', optional(string())], apiKey: ['apiKey', optional(string())] }
);
