/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsJavaUpdateProfileCommand {
  name?: string;
}

export const credentialsJavaUpdateProfileCommandSchema: Schema<CredentialsJavaUpdateProfileCommand> = object(
  { name: ['name', optional(string())] }
);
