/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import {
  CredentialsGitUpsertCommandBasicType,
  credentialsGitUpsertCommandBasicTypeSchema,
} from './credentialsGitUpsertCommandBasicType';
import {
  CredentialsGitUpsertCommandOAuthType,
  credentialsGitUpsertCommandOAuthTypeSchema,
} from './credentialsGitUpsertCommandOAuthType';

export interface CredentialsGitUpsertCommand {
  name?: string;
  email?: string;
  oAuth?: CredentialsGitUpsertCommandOAuthType | null;
  basic?: CredentialsGitUpsertCommandBasicType | null;
}

export const credentialsGitUpsertCommandSchema: Schema<CredentialsGitUpsertCommand> = object(
  {
    name: ['name', optional(string())],
    email: ['email', optional(string())],
    oAuth: [
      'oAuth',
      optional(
        nullable(lazy(() => credentialsGitUpsertCommandOAuthTypeSchema))
      ),
    ],
    basic: [
      'basic',
      optional(
        nullable(lazy(() => credentialsGitUpsertCommandBasicTypeSchema))
      ),
    ],
  }
);
