/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsCSharpUpsertCommand {
  name?: string;
  source?: string;
  apiKey?: string;
}

export const credentialsCSharpUpsertCommandSchema: Schema<CredentialsCSharpUpsertCommand> = object(
  {
    name: ['name', optional(string())],
    source: ['source', optional(string())],
    apiKey: ['apiKey', optional(string())],
  }
);
