/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsPhpUpsertCommand {
  name?: string;
  userName?: string;
  apiToken?: string;
}

export const credentialsPhpUpsertCommandSchema: Schema<CredentialsPhpUpsertCommand> = object(
  {
    name: ['name', optional(string())],
    userName: ['userName', optional(string())],
    apiToken: ['apiToken', optional(string())],
  }
);
