/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsPythonUpsertCommand {
  name?: string;
  token?: string;
}

export const credentialsPythonUpsertCommandSchema: Schema<CredentialsPythonUpsertCommand> = object(
  { name: ['name', optional(string())], token: ['token', optional(string())] }
);
