/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface CredentialsGitUpsertCommandOAuthType {
  provider?: string | null;
  code?: string | null;
  csrfToken?: string | null;
}

export const credentialsGitUpsertCommandOAuthTypeSchema: Schema<CredentialsGitUpsertCommandOAuthType> = object(
  {
    provider: ['provider', optional(nullable(string()))],
    code: ['code', optional(nullable(string()))],
    csrfToken: ['csrfToken', optional(nullable(string()))],
  }
);
