/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsTypeScriptUpsertCommand {
  name?: string;
  accessToken?: string;
}

export const credentialsTypeScriptUpsertCommandSchema: Schema<CredentialsTypeScriptUpsertCommand> = object(
  {
    name: ['name', optional(string())],
    accessToken: ['accessToken', optional(string())],
  }
);
