/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsGitUpdateProfileCommand {
  name?: string;
}

export const credentialsGitUpdateProfileCommandSchema: Schema<CredentialsGitUpdateProfileCommand> = object(
  { name: ['name', optional(string())] }
);
