/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CredentialsPythonUpdateProfileCommand {
  name?: string;
}

export const credentialsPythonUpdateProfileCommandSchema: Schema<CredentialsPythonUpdateProfileCommand> = object(
  { name: ['name', optional(string())] }
);
