/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface CredentialsGitUpsertCommandBasicType {
  urlOrProvider?: string | null;
  username?: string | null;
  tokenOrPassword?: string | null;
}

export const credentialsGitUpsertCommandBasicTypeSchema: Schema<CredentialsGitUpsertCommandBasicType> = object(
  {
    urlOrProvider: ['urlOrProvider', optional(nullable(string()))],
    username: ['username', optional(nullable(string()))],
    tokenOrPassword: ['tokenOrPassword', optional(nullable(string()))],
  }
);
