/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CSharpCredentialsItem {
  id?: string;
  name?: string;
  source?: string;
}

export const cSharpCredentialsItemSchema: Schema<CSharpCredentialsItem> = object(
  {
    id: ['id', optional(string())],
    name: ['name', optional(string())],
    source: ['source', optional(string())],
  }
);
