/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, nullable, object, optional, Schema, string } from '../schema';

export interface CSharpConfigurationItem {
  isEnabled?: boolean;
  credentialsId?: string;
  packageId?: string;
  authors?: string | null;
  description?: string | null;
  title?: string | null;
  packageTags?: string | null;
  repositoryUrl?: string | null;
  repositoryType?: string | null;
  packageProjectUrl?: string | null;
  packageIcon?: string | null;
  packageReadmeFile?: string | null;
  licenseFile?: string | null;
  packageReleaseNotes?: string | null;
  copyright?: string | null;
}

export const cSharpConfigurationItemSchema: Schema<CSharpConfigurationItem> = object(
  {
    isEnabled: ['isEnabled', optional(boolean())],
    credentialsId: ['credentialsId', optional(string())],
    packageId: ['packageId', optional(string())],
    authors: ['authors', optional(nullable(string()))],
    description: ['description', optional(nullable(string()))],
    title: ['title', optional(nullable(string()))],
    packageTags: ['packageTags', optional(nullable(string()))],
    repositoryUrl: ['repositoryUrl', optional(nullable(string()))],
    repositoryType: ['repositoryType', optional(nullable(string()))],
    packageProjectUrl: ['packageProjectUrl', optional(nullable(string()))],
    packageIcon: ['packageIcon', optional(nullable(string()))],
    packageReadmeFile: ['packageReadmeFile', optional(nullable(string()))],
    licenseFile: ['licenseFile', optional(nullable(string()))],
    packageReleaseNotes: ['packageReleaseNotes', optional(nullable(string()))],
    copyright: ['copyright', optional(nullable(string()))],
  }
);
