/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface GitConfigurationItem {
  isEnabled?: boolean;
  credentialsId?: string;
  repositoryName?: string;
  branch?: string;
}

export const gitConfigurationItemSchema: Schema<GitConfigurationItem> = object({
  isEnabled: ['isEnabled', optional(boolean())],
  credentialsId: ['credentialsId', optional(string())],
  repositoryName: ['repositoryName', optional(string())],
  branch: ['branch', optional(string())],
});
