/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface GitCredentialsItem {
  id?: string;
  name?: string;
  urlOrProvider?: string;
  email?: string;
  username?: string;
}

export const gitCredentialsItemSchema: Schema<GitCredentialsItem> = object({
  id: ['id', optional(string())],
  name: ['name', optional(string())],
  urlOrProvider: ['urlOrProvider', optional(string())],
  email: ['email', optional(string())],
  username: ['username', optional(string())],
});
