/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import {
  CSharpConfigurationItem,
  cSharpConfigurationItemSchema,
} from './cSharpConfigurationItem';
import {
  GitConfigurationItem,
  gitConfigurationItemSchema,
} from './gitConfigurationItem';
import {
  GoConfigurationItem,
  goConfigurationItemSchema,
} from './goConfigurationItem';
import {
  JavaConfigurationItem,
  javaConfigurationItemSchema,
} from './javaConfigurationItem';
import {
  PhpConfigurationItem,
  phpConfigurationItemSchema,
} from './phpConfigurationItem';
import {
  PythonConfigurationItem,
  pythonConfigurationItemSchema,
} from './pythonConfigurationItem';
import {
  RubyConfigurationItem,
  rubyConfigurationItemSchema,
} from './rubyConfigurationItem';
import {
  SwiftConfigurationItem,
  swiftConfigurationItemSchema,
} from './swiftConfigurationItem';
import {
  TypeScriptConfigurationItem,
  typeScriptConfigurationItemSchema,
} from './typeScriptConfigurationItem';

export interface PublishingProfileItem {
  id?: string;
  name?: string;
  cSharpConfiguration?: CSharpConfigurationItem | null;
  goConfiguration?: GoConfigurationItem | null;
  javaConfiguration?: JavaConfigurationItem | null;
  phpConfiguration?: PhpConfigurationItem | null;
  pythonConfiguration?: PythonConfigurationItem | null;
  rubyConfiguration?: RubyConfigurationItem | null;
  swiftConfiguration?: SwiftConfigurationItem | null;
  typeScriptConfiguration?: TypeScriptConfigurationItem | null;
  cSharpGitConfiguration?: GitConfigurationItem | null;
  goGitConfiguration?: GitConfigurationItem | null;
  javaGitConfiguration?: GitConfigurationItem | null;
  phpGitConfiguration?: GitConfigurationItem | null;
  pythonGitConfiguration?: GitConfigurationItem | null;
  rubyGitConfiguration?: GitConfigurationItem | null;
  swiftGitConfiguration?: GitConfigurationItem | null;
  typeScriptGitConfiguration?: GitConfigurationItem | null;
}

export const publishingProfileItemSchema: Schema<PublishingProfileItem> = object(
  {
    id: ['id', optional(string())],
    name: ['name', optional(string())],
    cSharpConfiguration: [
      'cSharpConfiguration',
      optional(nullable(lazy(() => cSharpConfigurationItemSchema))),
    ],
    goConfiguration: [
      'goConfiguration',
      optional(nullable(lazy(() => goConfigurationItemSchema))),
    ],
    javaConfiguration: [
      'javaConfiguration',
      optional(nullable(lazy(() => javaConfigurationItemSchema))),
    ],
    phpConfiguration: [
      'phpConfiguration',
      optional(nullable(lazy(() => phpConfigurationItemSchema))),
    ],
    pythonConfiguration: [
      'pythonConfiguration',
      optional(nullable(lazy(() => pythonConfigurationItemSchema))),
    ],
    rubyConfiguration: [
      'rubyConfiguration',
      optional(nullable(lazy(() => rubyConfigurationItemSchema))),
    ],
    swiftConfiguration: [
      'swiftConfiguration',
      optional(nullable(lazy(() => swiftConfigurationItemSchema))),
    ],
    typeScriptConfiguration: [
      'typeScriptConfiguration',
      optional(nullable(lazy(() => typeScriptConfigurationItemSchema))),
    ],
    cSharpGitConfiguration: [
      'cSharpGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    goGitConfiguration: [
      'goGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    javaGitConfiguration: [
      'javaGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    phpGitConfiguration: [
      'phpGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    pythonGitConfiguration: [
      'pythonGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    rubyGitConfiguration: [
      'rubyGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    swiftGitConfiguration: [
      'swiftGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
    typeScriptGitConfiguration: [
      'typeScriptGitConfiguration',
      optional(nullable(lazy(() => gitConfigurationItemSchema))),
    ],
  }
);
