/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface PythonCredentialsItem {
  id?: string;
  name?: string;
}

export const pythonCredentialsItemSchema: Schema<PythonCredentialsItem> = object(
  { id: ['id', optional(string())], name: ['name', optional(string())] }
);
