/**
 * PackagePublishing.WebLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema, string } from '../schema';

export interface SwiftConfigurationItem {
  isEnabled?: boolean;
  credentialsId?: string;
}

export const swiftConfigurationItemSchema: Schema<SwiftConfigurationItem> = object(
  {
    isEnabled: ['isEnabled', optional(boolean())],
    credentialsId: ['credentialsId', optional(string())],
  }
);
